package app.model.bo;
// Generated 29 mars 2020 18:39:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Article generated by hbm2java
 */
public class Article  implements java.io.Serializable {


     private Integer idArticle;
     private String image;
     private int nbStock;
     private double prix;
     private String categorie;
     private String description;
     private Set<Ligne> lignes = new HashSet<Ligne>(0);

    public Article() {
    }

	
    public Article(String image, int nbStock, double prix, String categorie, String description) {
        this.image = image;
        this.nbStock = nbStock;
        this.prix = prix;
        this.categorie = categorie;
        this.description = description;
    }
    public Article(String image, int nbStock, double prix, String categorie, String description, Set<Ligne> lignes) {
       this.image = image;
       this.nbStock = nbStock;
       this.prix = prix;
       this.categorie = categorie;
       this.description = description;
       this.lignes = lignes;
    }
   
    public Integer getIdArticle() {
        return this.idArticle;
    }
    
    public void setIdArticle(Integer idArticle) {
        this.idArticle = idArticle;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public int getNbStock() {
        return this.nbStock;
    }
    
    public void setNbStock(int nbStock) {
        this.nbStock = nbStock;
    }
    public double getPrix() {
        return this.prix;
    }
    
    public void setPrix(double prix) {
        this.prix = prix;
    }
    public String getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(String categorie) {
        this.categorie = categorie;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<Ligne> getLignes() {
        return this.lignes;
    }
    
    public void setLignes(Set<Ligne> lignes) {
        this.lignes = lignes;
    }




}


