package app.model.bo;
// Generated 29 mars 2020 18:39:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer idClient;
     private String nom;
     private String prenom;
     private String email;
     private String mdp;
     private String adresse;
     private String tele;
     private Set<Panier> paniers = new HashSet<Panier>(0);

    public Client() {
    }

	
    public Client(String nom, String prenom, String email, String mdp, String adresse, String tele) {
        this.nom = nom;
        this.prenom = prenom;
        this.email = email;
        this.mdp = mdp;
        this.adresse = adresse;
        this.tele = tele;
    }
    public Client(String nom, String prenom, String email, String mdp, String adresse, String tele, Set<Panier> paniers) {
       this.nom = nom;
       this.prenom = prenom;
       this.email = email;
       this.mdp = mdp;
       this.adresse = adresse;
       this.tele = tele;
       this.paniers = paniers;
    }
   
    public Integer getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMdp() {
        return this.mdp;
    }
    
    public void setMdp(String mdp) {
        this.mdp = mdp;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getTele() {
        return this.tele;
    }
    
    public void setTele(String tele) {
        this.tele = tele;
    }
    public Set<Panier> getPaniers() {
        return this.paniers;
    }
    
    public void setPaniers(Set<Panier> paniers) {
        this.paniers = paniers;
    }




}


