package app.model.bo;
// Generated 29 mars 2020 18:39:04 by Hibernate Tools 4.3.1



/**
 * LigneId generated by hbm2java
 */
public class LigneId  implements java.io.Serializable {


     private int idPanier;
     private int idArticle;

    public LigneId() {
    }

    public LigneId(int idPanier, int idArticle) {
       this.idPanier = idPanier;
       this.idArticle = idArticle;
    }
   
    public int getIdPanier() {
        return this.idPanier;
    }
    
    public void setIdPanier(int idPanier) {
        this.idPanier = idPanier;
    }
    public int getIdArticle() {
        return this.idArticle;
    }
    
    public void setIdArticle(int idArticle) {
        this.idArticle = idArticle;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LigneId) ) return false;
		 LigneId castOther = ( LigneId ) other; 
         
		 return (this.getIdPanier()==castOther.getIdPanier())
 && (this.getIdArticle()==castOther.getIdArticle());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPanier();
         result = 37 * result + this.getIdArticle();
         return result;
   }   


}


