package app.model.bo;
// Generated 29 mars 2020 18:39:04 by Hibernate Tools 4.3.1



/**
 * Ligne generated by hbm2java
 */
public class Ligne  implements java.io.Serializable {


     private LigneId id;
     private Article article;
     private Panier panier;
     private int quantite;

    public Ligne() {
    }

    public Ligne(LigneId id, Article article, Panier panier, int quantite) {
       this.id = id;
       this.article = article;
       this.panier = panier;
       this.quantite = quantite;
    }
   
    public LigneId getId() {
        return this.id;
    }
    
    public void setId(LigneId id) {
        this.id = id;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    public Panier getPanier() {
        return this.panier;
    }
    
    public void setPanier(Panier panier) {
        this.panier = panier;
    }
    public int getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(int quantite) {
        this.quantite = quantite;
    }




}


