package app.model.bo;
// Generated 29 mars 2020 18:39:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Panier generated by hbm2java
 */
public class Panier  implements java.io.Serializable {


     private Integer idPanier;
     private Client client;
     private boolean etat;
     private Set<Ligne> lignes = new HashSet<Ligne>(0);

    public Panier() {
    }

	
    public Panier(Client client, boolean etat) {
        this.client = client;
        this.etat = etat;
    }
    public Panier(Client client, boolean etat, Set<Ligne> lignes) {
       this.client = client;
       this.etat = etat;
       this.lignes = lignes;
    }
   
    public Integer getIdPanier() {
        return this.idPanier;
    }
    
    public void setIdPanier(Integer idPanier) {
        this.idPanier = idPanier;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public boolean isEtat() {
        return this.etat;
    }
    
    public void setEtat(boolean etat) {
        this.etat = etat;
    }
    public Set<Ligne> getLignes() {
        return this.lignes;
    }
    
    public void setLignes(Set<Ligne> lignes) {
        this.lignes = lignes;
    }




}


